site_name: Firebrick

nav:
    - Home: index.md
    - Installtion: installtion.md
    - Settings: settings.md
    - Commands: commands.md
    - Basic Tests: tests/basic.md
    - Individual Tests: tests/individual.md
    - Asserts: tests/asserts.md
theme: readthedocs